# Generated by Django 5.0.6 on 2026-07-28 23:32

import django.contrib.auth.validators
from django.db import migrations, models


def populate_usernames(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    used = set()
    for user in User.objects.filter(username__isnull=True):
        base = user.email.split('@')[0] or f'user{user.pk}'
        candidate = base
        i = 1
        while candidate in used or User.objects.filter(username=candidate).exclude(pk=user.pk).exists():
            i += 1
            candidate = f'{base}{i}'
        used.add(candidate)
        user.username = candidate
        user.save(update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
    ]

    operations = [
        migrations.RunPython(populate_usernames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='nombre de usuario'),
        ),
    ]
